### ISSUE TITLE
As a community or team member, I want to be able to communicate with Topl through a messaging app

### ISSUE THREAD

**Issue by c-georgen** [Topl/Project-Bifrost#18]
Topl needs to move away from Slack as a messaging application to ensure greater control over the community, specifically to prevent users from being able to send private messages impersonating members of the team. We prefer an open-source, self-hosted platform to control costs and maximize functionality.

#### Sub-tasks

- [ ] Select between Rocket.Chat, Mattermost, Riot.im, or another option
- [ ] Deploy and setup chat server
- [ ] Test
- [ ] Migrate core team
- [ ] Begin migration of community

**Comment by c-georgen** [comment]
Issue placed in wrong repo
